# Generated by Django 3.1.2 on 2020-10-22 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otptabl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=35, unique=True)),
                ('Otp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='parmtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parm_id', models.CharField(max_length=4, unique=True)),
                ('parm_key', models.CharField(max_length=35, unique=True)),
                ('parm_data', models.CharField(max_length=100)),
                ('parm_dsec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RplUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30, unique=True)),
                ('emailId', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('activeflag', models.BooleanField(default=False)),
                ('pwd', models.CharField(max_length=1000)),
                ('UserImg', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('seriesId', models.IntegerField(default=0)),
                ('matchId', models.IntegerField()),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('player3', models.CharField(max_length=100)),
                ('player4', models.CharField(max_length=100)),
                ('player5', models.CharField(max_length=100)),
                ('bat1', models.FloatField(default=0)),
                ('bat2', models.FloatField(default=0)),
                ('bowl1', models.FloatField(default=0)),
                ('bowl2', models.FloatField(default=0)),
                ('allround', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('point', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
            options={
                'unique_together': {('userName', 'matchId', 'seriesId')},
            },
        ),
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.IntegerField(blank=True, null=True)),
                ('teamDisName', models.CharField(blank=True, max_length=100, null=True)),
                ('teamName', models.CharField(blank=True, max_length=10, null=True)),
                ('playerId', models.IntegerField(blank=True, null=True)),
                ('playerName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('teamId', 'playerId')},
            },
        ),
    ]
