# Generated by Django 3.0.6 on 2020-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpl31', '0002_otptabl'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected',
            name='seriesId',
            field=models.IntegerField(default=0),
        ),
    ]
