# Generated by Django 3.0.6 on 2020-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpl31', '0004_auto_20200904_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected',
            name='point',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
