# Generated by Django 3.0.6 on 2020-10-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpl31', '0005_auto_20200930_1500'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selected',
            unique_together={('userName', 'matchId', 'seriesId')},
        ),
    ]
