# Generated by Django 3.1.7 on 2021-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpl31', '0008_auto_20210312_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rplusers',
            name='UserImg',
        ),
        migrations.AlterField(
            model_name='rplusers',
            name='image',
            field=models.FileField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
