# Generated by Django 3.1.7 on 2021-03-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpl31', '0009_auto_20210312_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='rplusers',
            name='UserImg',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
