# Generated by Django 3.1.7 on 2021-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpl31', '0010_rplusers_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rplusers',
            name='image',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
