# Generated by Django 3.1.7 on 2021-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpl31', '0011_auto_20210312_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rplusers',
            name='UserImg',
        ),
        migrations.AlterField(
            model_name='rplusers',
            name='image',
            field=models.FileField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rplusers',
            name='image_data',
            field=models.BinaryField(default=b'\x08', null=True),
        ),
    ]
